version: 2
jobs:
  build:
    working_directory: /usr/src/prologue
    docker:
      - image: nimlang/nim
    steps:
      - checkout
      - run:
          name: refresh
          command: nimble refresh
      - run:
          name: intall
          command: nimble install -y
      - run:
          name: extension
          command: nimble extension
      - run:
          name: compile
          command: nimble tcompile
      - run:
          name: readme
          command: nimble treadme
      - run:
          name: examples
          command: nimble texamples

  build_alpine:
    working_directory: /usr/src/prologue
    docker:
      - image: nimlang/nim:alpine
    steps:
      - checkout
      - run:
          name: refresh
          command: nimble refresh
      - run:
          name: intall
          command: nimble install -y
      - run:
          name: extension
          command: nimble extension
      - run:
          name: compile
          command: nimble tcompile
      - run:
          name: readme
          command: nimble treadme
      - run:
          name: examples
          command: nimble texamples

  test_app:
    working_directory: /usr/src/prologue
    docker:
      - image: nimlang/nim
    steps:
      - checkout
      - run:
          name: refresh
          command: nimble refresh
      - run:
          name: intall
          command: nimble install -y
      - run:
          name: extension
          command: nimble extension

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - build_alpine
